### PR TITLE
Handle user removed after making an invitation.

### LINKED ISSUE #179: Invitations: Deletion of an inviter breaks GET /invitations endpoint
Steps to reproduce:

1. Create an invitation to Organization A with a custom inviter (User B)
2. Delete User B
3. Request invitations for Organization A

Expected result: 200 with a list of existing invitations
Actual result: 400 with message {"error":"unknown_error"}

### PR DESCRIPTION
**Pull request by xgp**
return null for inviter if the user was removed. lazy removed the inviterId. fixes #179

### CODE REVIEW

File: src/main/java/io/phasetwo/service/model/jpa/InvitationAdapter.java [hunk 1]
```diff
@@ -74,10 +74,16 @@ public void setUrl(String url) {
...
-      return session.users().getUserById(realm, invitation.getInviterId());
-    } else {
-      return null;
+      UserModel inviter = session.users().getUserById(realm, invitation.getInviterId());
+      // it is possible that the inviter was removed
+      if (inviter != null) {
+        return inviter;
+      } else {
+        // lazy remove the inviterId
+        invitation.setInviterId(null);
```
Comment (rtufisi) [inline src/main/java/io/phasetwo/service/model/jpa/InvitationAdapter.java:83]: We could add a e event to remove the invitation in the future. I saw the comment on the task

**Review by rtufisi — APPROVED** [review]
