### PR TITLE
fix: use inviter instead current authed user for invitation

### LINKED ISSUE #49: Invite Email with necessary params missing
Hi,

Just starting to try out keycloak-orgs (thanks for open sourcing this!) and stumbled upon the invite email sent having missing params:

```
michael@example.org has been invited to join Personal at MyRealm by . To accept or reject this invitation, click on the link below to log in.
```

That's the full email. No link is below and the inviter param is empty too even though the inviter has firstname/lastname and email. 
Any clue why that doesn't work?

FTR using keycloak-orgs at HEAD `80b4af5b1fd1a207ce5505c24eaf33b4568c80e0`.

### PR DESCRIPTION
**Pull request by mweibel**
fixes #49

### CODE REVIEW

File: src/main/java/io/phasetwo/service/resource/InvitationsResource.java [hunk 1]
```diff
@@ -83,7 +83,9 @@ public Response createInvitation(@Valid InvitationRequest invitation) {
     }
 
     try {
-      InvitationModel i = organization.addInvitation(email, auth.getUser());
+      UserModel inviter = session.users().getUserById(realm, invitation.getInviterId());
```
Comment (xgp) [inline src/main/java/io/phasetwo/service/resource/InvitationsResource.java:86]: For backwards compatibility, I'd like to have it fall back to `auth.getUser()` if the inviterId is null/empty.

**Review by xgp — CHANGES_REQUESTED** [review]

File: src/main/java/io/phasetwo/service/resource/InvitationsResource.java (hunk 1 above)
Comment (mweibel) [reply src/main/java/io/phasetwo/service/resource/InvitationsResource.java]: @xgp thx for review - updated the code in question. LMK if it's all right or there are better ways - my Java is a bit rusty unfortunately :)
